### ISSUE TITLE
GPU process isn't usable

### ISSUE THREAD

**Issue by thankph** [easymineable/easymineable#2]
Receiving the following error when executing the app image:  

`$ ./easymineable-desktop-2.1.0-linux-x86_64.AppImage 
[3652149:1114/203403.416949:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
`

Installed GPU is a Nvida GTX 1070  with the following driver: NVIDIA-Linux-x86_64-470.74

OS: 
Fedora 35, Kernel: 5.14.16-301.fc35.x86_64

What that error mean?

**Comment by NikitinGs** [comment]
Try adding --disable-gpu-sandbox flag, Nvidia drivers on OpenSuse and Fedora may work bad with electron apps
